version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  train:
    format: '%(asctime)s - %(name)s - %(levelname)s - Training finished after %(message)s seconds'
    datefmt: '%Y-%m-%d %H:%M:%S'
  csv:
    format: '%(asctime)s.%(msecs)03d,%(name)s,%(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  examples:
    format: '%(asctime)s.%(msecs)03d;%(name)s;%(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  las:
    format: '%(message)s'
  clingo:
    format: '%(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  train_console:
    class: logging.StreamHandler
    level: INFO
    formatter: train
    stream: ext://sys.stdout
  train:
    class: logging.FileHandler
    level: INFO
    formatter: csv
    filename: "./logs/timing/{run_id}_train.csv"
    mode: w
  steps:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: csv
    filename: "./logs/timing/{run_id}_steps.csv"
    mode: w
    maxBytes: 104857600
    backupCount: 10
  detect_objects:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: csv
    filename: "./logs/timing/symbolic/{run_id}_detect_objects.csv"
    mode: w
    maxBytes: 104857600
    backupCount: 10
  position_objects:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: csv
    filename: "./logs/timing/symbolic/{run_id}_position_objects.csv"
    mode: w
    maxBytes: 104857600
    backupCount: 10
  track_action:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: csv
    filename: "./logs/timing/symbolic/{run_id}_track_action.csv"
    mode: w
    maxBytes: 104857600
    backupCount: 10
  try_induction:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: csv
    filename: "./logs/timing/symbolic/{run_id}_try_induction.csv"
    mode: w
    maxBytes: 10485760
    backupCount: 100
  choose_action:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: csv
    filename: "./logs/timing/symbolic/{run_id}_choose_action.csv"
    mode: w
    maxBytes: 104857600
    backupCount: 10
  choose_action_ddqn:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: csv
    filename: "./logs/timing/symbolic/{run_id}_choose_action_ddqn.csv"
    mode: w
    maxBytes: 104857600
    backupCount: 10
  game_episodes:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: csv
    filename: "./logs/explain/{run_id}_episodes.csv"
    mode: w
    maxBytes: 104857600
    backupCount: 10
  game_steps:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: csv
    filename: "./logs/explain/{run_id}_steps.csv"
    mode: w
    maxBytes: 104857600
    backupCount: 10
  examples_positive:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: examples
    filename: "./logs/explain/{run_id}_examples_positive.csv"
    mode: w
    maxBytes: 104857600
    backupCount: 10
  examples_negative:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: examples
    filename: "./logs/explain/{run_id}_examples_negative.csv"
    mode: w
    maxBytes: 104857600
    backupCount: 10
  advice_given:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: examples
    filename: "./logs/explain/{run_id}_advice_given.csv"
    mode: w
    maxBytes: 104857600
    backupCount: 10
  advice_given_ddqn:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: examples
    filename: "./logs/explain/{run_id}_advice_given_ddqn.csv"
    mode: w
    maxBytes: 104857600
    backupCount: 10
  partial_interpretations_pos:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: las
    filename: "../asp/examples/{run_id}_positive.las"
    mode: w
    maxBytes: 10485760
    backupCount: 100
  partial_interpretations_neg:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: las
    filename: "../asp/examples/{run_id}_negative.las"
    mode: w
    maxBytes: 10485760
    backupCount: 100
  ilasp_program:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: las
    filename: "../asp/advice/{run_id}_ilasp.las"
    mode: w
    maxBytes: 10485760
    backupCount: 100
  induced_asp:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: clingo
    filename: "../asp/advice/{run_id}_advice.lp"
    mode: w
    maxBytes: 10485760
    backupCount: 100
loggers:
  train:
    level: INFO
    handlers: [train,train_console]
    propagate: no
  steps:
    level: INFO
    handlers: [steps]
    propagate: no
  detect_objects:
    level: INFO
    handlers: [detect_objects]
    propagate: no
  position_objects:
    level: INFO
    handlers: [position_objects]
    propagate: no
  track_action:
    level: INFO
    handlers: [track_action]
    propagate: no
  try_induction:
    level: INFO
    handlers: [try_induction]
    propagate: no
  choose_action:
    level: INFO
    handlers: [choose_action]
    propagate: no
  choose_action_ddqn:
    level: INFO
    handlers: [choose_action_ddqn]
    propagate: no
  game_episodes:
    level: INFO
    handlers: [game_episodes]
    propagate: no
  game_steps:
    level: INFO
    handlers: [game_steps]
    propagate: no
  examples_positive:
    level: INFO
    handlers: [examples_positive]
    propagate: no
  examples_negative:
    level: INFO
    handlers: [examples_negative]
    propagate: no
  advice_given:
    level: INFO
    handlers: [advice_given]
    propagate: no
  advice_given_ddqn:
    level: INFO
    handlers: [advice_given_ddqn]
    propagate: no
  partial_interpretations_pos:
    level: INFO
    handlers: [partial_interpretations_pos]
    propagate: no
  partial_interpretations_neg:
    level: INFO
    handlers: [partial_interpretations_neg]
    propagate: no
  ilasp_program:
    level: INFO
    handlers: [ilasp_program]
    propagate: no
  induced_asp:
    level: INFO
    handlers: [induced_asp]
    propagate: no
root:
  level: DEBUG
  handlers: [console]