version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  train:
    format: '%(asctime)s - %(name)s - %(levelname)s - Training finished after %(message)s seconds'
    datefmt: '%Y-%m-%d %H:%M:%S'
  csv:
    format: '%(asctime)s.%(msecs)03d,%(name)s,%(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  examples:
    format: '%(asctime)s.%(msecs)03d;%(name)s;%(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  las:
    format: '%(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  train_console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: train
    stream: ext://sys.stdout
  train:
    class: logging.FileHandler
    level: INFO
    formatter: csv
    filename: "./logs/timing/{run_id}_train.csv"
    mode: w
  steps:
    class: logging.FileHandler
    level: INFO
    formatter: csv
    filename: "./logs/timing/{run_id}_steps.csv"
    mode: w
  game_episodes:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: csv
    filename: "./logs/game/{run_id}_episodes.csv"
    mode: w
    maxBytes: 10485760
    backupCount: 10
  game_steps:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: csv
    filename: "./logs/game/{run_id}_steps.csv"
    mode: w
    maxBytes: 10485760
    backupCount: 10
  detect_objects:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: csv
    filename: "./logs/timing/symbolic/{run_id}_detect.csv"
    mode: w
    maxBytes: 10485760
    backupCount: 10
  position_objects:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: csv
    filename: "./logs/timing/symbolic/{run_id}_position.csv"
    mode: w
    maxBytes: 10485760
    backupCount: 10
  actions:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: csv
    filename: "./logs/timing/symbolic/{run_id}_actions.csv"
    mode: w
    maxBytes: 10485760
    backupCount: 10
  examples_positive:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: examples
    filename: "./logs/examples/{run_id}_examples_positive.csv"
    mode: w
    maxBytes: 10485760
    backupCount: 10
  examples_negative:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: examples
    filename: "./logs/examples/{run_id}_examples_negative.csv"
    mode: w
    maxBytes: 10485760
    backupCount: 10
  partial_interpretations_pos:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: las
    filename: "./asp/ilasp/{run_id}_positive.las"
    mode: w
    maxBytes: 1024
    backupCount: 2
  partial_interpretations_neg:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: las
    filename: "./asp/ilasp/{run_id}_negative.las"
    mode: w
    maxBytes: 1024
    backupCount: 2
  advice:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: examples
    filename: "./logs/advice/{run_id}_advice.csv"
    mode: w
    maxBytes: 10485760
    backupCount: 10
loggers:
  train:
    level: INFO
    handlers: [train,train_console]
    propagate: no
  steps:
    level: INFO
    handlers: [steps]
    propagate: no
  game_episodes:
    level: INFO
    handlers: [game_episodes]
    propagate: no
  game_steps:
    level: INFO
    handlers: [game_steps]
    propagate: no
  detection:
    level: INFO
    handlers: [detect_objects]
    propagate: no
  positioning:
    level: INFO
    handlers: [position_objects]
    propagate: no
  actions:
    level: INFO
    handlers: [actions]
    propagate: no
  examples_positive:
    level: INFO
    handlers: [examples_positive]
    propagate: no
  examples_negative:
    level: INFO
    handlers: [examples_negative]
    propagate: no
  partial_interpretations_pos:
    level: INFO
    handlers: [partial_interpretations_pos]
    propagate: no
  partial_interpretations_neg:
    level: INFO
    handlers: [partial_interpretations_neg]
    propagate: no
  advice:
    level: INFO
    handlers: [advice]
    propagate: no
root:
  level: DEBUG
  handlers: [console]