version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  train:
    format: '%(asctime)s - %(name)s - %(levelname)s - Training finished after %(message)s seconds'
    datefmt: '%Y-%m-%d %H:%M:%S'
  csv:
    format: '%(asctime)s.%(msecs)03d,%(name)s,%(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  train_console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: train
    stream: ext://sys.stdout
  train:
    class: logging.FileHandler
    level: INFO
    formatter: csv
    filename: "./logs/timing/{run_id}_train.csv"
    mode: w
  game_episodes:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: csv
    filename: "./logs/game/{run_id}_episodes.csv"
    mode: w
    maxBytes: 10485760
    backupCount: 10
  game_steps:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: csv
    filename: "./logs/game/{run_id}_steps.csv"
    mode: w
    maxBytes: 10485760
    backupCount: 10
loggers:
  train:
    level: INFO
    handlers: [train,train_console]
    propagate: no
  game_episodes:
    level: INFO
    handlers: [episodes]
    propagate: no
  game_steps:
    level: INFO
    handlers: [game_steps]
    propagate: no
root:
  level: DEBUG
  handlers: [console]