version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  csv:
    format: '%(asctime)s.%(msecs)03d,%(name)s,%(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  examples:
    format: '%(asctime)s.%(msecs)03d;%(name)s;%(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  detect_objects:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: csv
    filename: "./logs/timing/{run_id}_detect.csv"
    mode: w
    maxBytes: 10485760
    backupCount: 10
  position_objects:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: csv
    filename: "./logs/timing/{run_id}_position.csv"
    mode: w
    maxBytes: 10485760
    backupCount: 10
  episodes:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: csv
    filename: "./logs/timing/{run_id}_episodes.csv"
    mode: w
    maxBytes: 10485760
    backupCount: 10
  actions:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: csv
    filename: "./logs/timing/{run_id}_actions.csv"
    mode: w
    maxBytes: 10485760
    backupCount: 10
  examples_positive:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: examples
    filename: "./logs/examples/{run_id}_examples_positive.csv"
    mode: w
    maxBytes: 10485760
    backupCount: 10
  examples_negative:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: examples
    filename: "./logs/examples/{run_id}_examples_negative.csv"
    mode: w
    maxBytes: 10485760
    backupCount: 10
loggers:
  detection:
    level: INFO
    handlers: [detect_objects]
    propagate: no
  positioning:
    level: INFO
    handlers: [position_objects]
    propagate: no
  episodes:
    level: INFO
    handlers: [episodes]
    propagate: no
  actions:
    level: INFO
    handlers: [actions]
    propagate: no
  examples_positive:
    level: INFO
    handlers: [examples_positive]
    propagate: no
  examples_negative:
    level: INFO
    handlers: [examples_negative]
    propagate: no
  production:
    level: WARNING
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]